- apt:
    update_cache: yes

- apt:
    name:
      - fontconfig
      - openjdk-21-jre
    state: present
    
- file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'


- get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
    dest: /etc/apt/keyrings/jenkins-keyring.asc
    mode: '0644'

- copy:
    content: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    dest: /etc/apt/sources.list.d/jenkins.list

- apt:
    update_cache: yes

- apt: 
    name: jenkins 
    state: present

- systemd:
    name: jenkins
    enabled: yes
    state: started
